name = "BayesPlots"
uuid = "193c7f83-fc3f-40b4-b16f-ec9e6feb51fb"
authors = ["KaoruBB <kaorugmbl1234@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
KernelDensity = "5ab0869b-81aa-558d-bb23-cbf5423bbe9b"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"

[compat]
KernelDensity = "0.6.9"
Plots = "1.40.8"
StatsBase = "0.34.3"
StatsPlots = "0.15.7"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
